import type {QS} from './game'
export interface Level{id:string;name:string;idea:string;hint:string;ar:{name:string;idea:string;hint:string};target:QS;diff:number;points:number;par:number;grid:string[]}
export const LEVELS:Level[]=[
 {id:"L1",name:"Level 1 · Bit Flip",idea:"Gates change your state the moment you step on them.",hint:"You begin as |0⟩ and the exit wants a different state. Several gates on this map change your state, and every step onto one counts. Plan your route before you rush.",ar:{name:"المرحلة 1 · قلب البت",idea:"البوابات تغيّر حالتك بمجرد أن تمرّ فوقها.",hint:"تبدأ بالحالة |0⟩ والمخرج يريد حالة مختلفة. عدة بوابات على الخريطة تغيّر حالتك، وكل مرور فوق بوابة يُحتسب. خطّط لمسارك قبل أن تتسرّع."},target:'1',diff:1,points:500,par:40,grid:["#################","#......X#E......#","#.#.#.#.###.###.#","#......X..#.#...#","#########X#.#.#.#","#.......#.#.#.#.#","#C#.###.#.###.#.#","#...#.#.#..S..#.#","#...#.#.###.###.#","#.....#.C......C#","#################"]},
 {id:"L2",name:"Level 2 · Superposition",idea:"Applying the same gate twice cancels it out.",hint:"H turns a definite state into a superposition, and turns it back if you step on it again. Count how many H gates your whole route crosses. Does it end odd or even?",ar:{name:"المرحلة 2 · التراكب",idea:"تطبيق البوابة نفسها مرتين يلغي أثرها.",hint:"بوابة H تحوّل الحالة الأساسية إلى تراكب، وتعيدها إلى ما كانت عليه إذا مررت فوقها مرة أخرى. احسب كم بوابة H يعبر مسارك كله. هل العدد فردي أم زوجي؟"},target:'+',diff:2,points:800,par:45,grid:["#################","#E.C......#C....#","###.#####.#.#.#.#","#...#...#.#.....#","#.#.#.#.#.#.###.#","#...#.H.#.....#.#","#.###.#.#######.#","#.#...#...#..S..#","#.#.#####.#.#####","#.C....C#H...H.H#","#################"]},
 {id:"L3",name:"Level 3 · Hidden Phase",idea:"Some gates only matter once you are in superposition.",hint:"Z looks useless on |0⟩ or |1⟩. It only shows its power on a superposition. Order matters: the same two gates in the opposite order can give a different result.",ar:{name:"المرحلة 3 · الطور الخفي",idea:"بعض البوابات لا يظهر أثرها إلا وأنت في حالة تراكب.",hint:"تبدو Z عديمة الفائدة على |0⟩ أو |1⟩، ولا تظهر قوتها إلا في التراكب. الترتيب مهم: البوابتان نفسهما بترتيب معاكس قد تعطيان نتيجة مختلفة."},target:'-',diff:3,points:1200,par:45,grid:["#################","#...#.........X.#","#.#.#.#########.#","#.#C..#...H...#E#","#.###.#C#.#######","#Z..#.....H.....#","#.#.#.#####.#H#.#","#.#S#C....#.C...#","#Z#.###########.#","#.#..Z..........#","#################"]},
 {id:"L4",name:"Level 4 · Measurement",idea:"Measuring destroys a superposition, but a definite state passes M untouched.",hint:"M sends a superposed qubit back to the start. Cross it only while you are definite. There is no X on this map, but a qubit can still reach |1⟩ the long way round.",ar:{name:"المرحلة 4 · القياس",idea:"القياس يُنهي التراكب، أما الحالة الأساسية فتعبر M دون أن تتأثر.",hint:"بوابة M تعيد الكيوبت المتراكب إلى نقطة البداية، فاعبرها وأنت في حالة أساسية فقط. لا توجد بوابة X في هذه الخريطة، لكن يمكن الوصول إلى |1⟩ عبر طريق أطول."},target:'1',diff:4,points:1700,par:60,grid:["#################","#...#.....#....M#","#.###H###M#.###.#","#.C.....#.#.ZE#.#","#M#.#####.#####Z#","#.#...#..C#.....#","#.###C###.#.#.#C#","#.#...H...M.#...#","#.#.#######.#.###","#...#.H........S#","#################"]},
 {id:"L5",name:"Level 5 · Undo",idea:"Every gate here is its own undo button.",hint:"The exit wants the very state you started with, but the maze drags you through gates on the way. What you apply you can take back, in the reverse order.",ar:{name:"المرحلة 5 · التراجع",idea:"كل بوابة هنا هي زر التراجع الخاص بها.",hint:"المخرج يريد الحالة نفسها التي بدأت بها، لكن المتاهة تجرّك عبر بوابات في الطريق. ما طبّقته يمكنك التراجع عنه، بالترتيب المعاكس."},target:'0',diff:5,points:2300,par:65,grid:["#################","#...#Z.C....#.C.#","#Z#.#######.#.#.#","#E#.....M.#.#...#","#######.#.#H###.#","#.C..H..#C#.....#","#.#####.#######.#","#Y.X....#..Y#M..#","#.#####M#.#.#.###","#....S#.C....H.X#","#################"]},
]
export const RACE:Level={id:"RACE",name:"The Grand Quantum Maze",idea:"Everything you learned, in one giant maze. And everybody is racing.",hint:"All five gates and five M traps are on this map. Don't grab the first thing you see: think about the state you want to be in every time you cross an M, and keep an eye on the scoreboard.",ar:{name:"المتاهة الكمومية الكبرى",idea:"كل ما تعلمته في متاهة واحدة ضخمة، والجميع يتسابق.",hint:"فيها كل البوابات الخمس وخمس بوابات M. لا تتسرّع في أول شيء تراه: فكّر في الحالة التي تريدها كلما عبرت M، وراقب لوحة الترتيب."},target:'-',diff:6,points:4000,par:90,grid:["#############################","#...M...C.....#....X........#","#.#########.###.#####.#.#.#.#","#.#E...M....#...#....C.M#.#.#","#.###.#######.###.###.#.#.#.#","#...#...#..M..#.......#...#.#","#.#Z#...#.#.#####.#Z#.#.###.#","#.#..C..#...#...#...#H.H..#.#","#.###.###.#.#.#.#.#.###.#.#.#","#...#..X..#.#C#...#.....#...#","#.#.#.###.#.#.###.###.#.#C###","#.H...#........H#.X.....#.#.#","#####.#.###.###.#####.S.#Z#Y#","#..M..#.........#...#...#...#","#.###############.#Y#.#.#...#","#...#..C....Z.....#.#.......#","#####.#.#.#.#.#.###C###...#.#","#C....#...#................Y#","#############################"]}
